name: Markdown Validation

on:
  pull_request:
    paths:
      - "**.md"

jobs:
  markdown:
    name: Validate Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "**/*.md"