name: Spell Check

on:
  pull_request:

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.md"